import { useEffect, useState } from "react";
import type { SourceId, SourceRecord, SourceRuntimeState } from "../contracts";
import type { AppDependencies } from "./dependencies";
import { initialRuntimeState, stateNeedsScan } from "./AppPrimitives";
type ScanListener = (state: SourceRuntimeState) => void;
interface SharedScan { readonly controller: AbortController; readonly listeners: Set<ScanListener>; }
const sharedScans = new WeakMap<AppDependencies["photoSource"], Map<SourceId, SharedScan>>();
function scansFor(photoSource: AppDependencies["photoSource"]) { let scans = sharedScans.get(photoSource); if (!scans) { scans = new Map(); sharedScans.set(photoSource, scans); } return scans; }
export function startSharedScan(photoSource: AppDependencies["photoSource"], sourceId: SourceId) { const scans = scansFor(photoSource); if (scans.has(sourceId)) return; const scan: SharedScan = { controller: new AbortController(), listeners: new Set() }; scans.set(sourceId, scan); void (async () => { for await (const result of photoSource.scan(sourceId, scan.controller.signal)) { if (!result.ok) { const failed = { ...initialRuntimeState(sourceId), status: "error" as const, errorMessage: "扫描失败，请重试。" }; scan.listeners.forEach((listener) => listener(failed)); break; } scan.listeners.forEach((listener) => listener(result.value.state)); } scans.delete(sourceId); })(); }
export function stopSharedScan(photoSource: AppDependencies["photoSource"], sourceId: SourceId) { scansFor(photoSource).get(sourceId)?.controller.abort(); }
export function useSourceMonitor(photoSource: AppDependencies["photoSource"], sources: readonly SourceRecord[]) { const [states, setStates] = useState<Record<string, SourceRuntimeState>>({}); const sourceKey = sources.map((source) => source.id).join(","); const startScan = (sourceId: SourceId) => startSharedScan(photoSource, sourceId); useEffect(() => { let active = true; const scans = scansFor(photoSource); const unsubscribers = sources.map((source) => { const listener: ScanListener = (state) => { if (active) setStates((current) => ({ ...current, [source.id]: state })); }; scans.get(source.id)?.listeners.add(listener); void photoSource.getSourceState(source.id).then((result) => { if (!active || !result.ok) return; setStates((current) => ({ ...current, [source.id]: result.value })); if (stateNeedsScan(result.value)) startSharedScan(photoSource, source.id); scans.get(source.id)?.listeners.add(listener); }); return () => scans.get(source.id)?.listeners.delete(listener); }); return () => { active = false; unsubscribers.forEach((unsubscribe) => unsubscribe()); }; }, [photoSource, sourceKey]); return { states, startScan }; }
