import { expect, test } from "@playwright/test";

test("creates and edits a Frame on the Table and restores it after reload", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "Projects" })).toBeVisible();
  const projectId = `frame-e2e-${crypto.randomUUID()}`;
  await page.evaluate(async (id) => {
    const request = indexedDB.open("photoflex-mvp");
    const db = await new Promise<IDBDatabase>((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
    const createdAt = new Date().toISOString();
    const transaction = db.transaction("projects", "readwrite");
    transaction.objectStore("projects").put({ schemaVersion: 10, projectId: id, name: "Frame Test", memo: "", expectedPhotoCount: null, sources: [], photoStates: {},
      worktableDraft: { projectId: id, entryOrder: [], placements: {}, groups: [], links: [], pileOrder: [], pilePlacements: {}, frameOrder: [], frames: {} },
      sequenceIds: [], versionIds: [], layoutIds: [], revision: 0, createdAt, updatedAt: createdAt, lastOpenedAt: createdAt });
    await new Promise<void>((resolve, reject) => { transaction.oncomplete = () => resolve(); transaction.onerror = () => reject(transaction.error); });
    db.close();
  }, projectId);
  await page.goto(`/#/projects/${projectId}/table`);
  await expect(page.getByLabel("Photo worktable")).toBeVisible();
  await page.getByRole("button", { name: "Frame templates" }).click();
  await page.getByRole("button", { name: /^Plain Page/ }).click();
  await page.getByRole("button", { name: /Quad Grid 4 slots/ }).click();
  const frame = page.locator("[data-frame-id]");
  await expect(frame).toHaveCount(1);
  await expect(frame.locator("[data-frame-slot-id]")).toHaveCount(4);
  const settings = page.getByRole("complementary", { name: "Frame settings" });
  await expect(settings).toBeVisible();
  await expect(page.getByRole("complementary", { name: "Photo Sources" })).toHaveCount(0);
  await settings.getByRole("button", { name: "Diptych", exact: true }).click();
  await expect(frame.locator("[data-frame-slot-id]")).toHaveCount(2);
  await settings.getByRole("button", { name: "Add photo box" }).click();
  await expect(frame.locator("[data-frame-slot-id]")).toHaveCount(3);
  await expect(settings.getByText("PHOTO BOX 03")).toBeVisible();
  await expect(settings.getByRole("group", { name: "Template" })).toBeVisible();
  await expect(settings.getByRole("slider", { name: "Corner radius" })).toBeVisible();
  await settings.getByRole("button", { name: "Remove photo box" }).click();
  await expect(frame.locator("[data-frame-slot-id]")).toHaveCount(2);
  await frame.locator("[data-frame-slot-id]").first().click();
  await page.keyboard.press("Delete");
  await expect(frame).toHaveCount(1);
  await expect(frame.locator("[data-frame-slot-id]")).toHaveCount(1);
  await settings.getByRole("button", { name: "Duplicate" }).click();
  await expect(page.locator("[data-frame-id]")).toHaveCount(2);
  await page.reload();
  await expect(page.locator("[data-frame-id]")).toHaveCount(2);
  await expect(page.locator("[data-frame-id]").first().locator("[data-frame-slot-id]")).toHaveCount(1);
  await page.locator("[data-frame-id]").first().click();
  await page.setViewportSize({ width: 1280, height: 800 });
  await page.locator("[data-frame-id]").last().locator(".table-frame-title").click({ position: { x: 50, y: 4 } });
  const inspector = await settings.boundingBox();
  const stage = await page.getByLabel("Photo worktable").boundingBox();
  expect(inspector && stage && inspector.x >= stage.x + stage.width && inspector.x + inspector.width <= 1280).toBeTruthy();
  await page.getByRole("button", { name: "Frame templates" }).click();
  const popover = page.getByRole("dialog", { name: "Frame templates" });
  await expect(popover).toBeVisible();
  const bounds = await popover.boundingBox();
  expect(bounds && bounds.x >= 0 && bounds.y >= 0 && bounds.x + bounds.width <= 1280 && bounds.y + bounds.height <= 800).toBeTruthy();
  await page.keyboard.press("Escape");
  await expect(popover).toBeHidden();
  await page.getByRole("button", { name: "Frame templates" }).click();
  await page.getByLabel("Photo worktable").click({ position: { x: 220, y: 100 } });
  await expect(popover).toBeHidden();
  await page.screenshot({ path: testInfo.outputPath("frame.png") });
});

test("creates a full-page square nine-grid and adds selected photo-box settings below Frame settings", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/");
  const projectId = `frame-nine-${crypto.randomUUID()}`;
  await page.evaluate(async (id) => {
    const request = indexedDB.open("photoflex-mvp");
    const db = await new Promise<IDBDatabase>((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
    const createdAt = new Date().toISOString();
    const transaction = db.transaction("projects", "readwrite");
    transaction.objectStore("projects").put({ schemaVersion: 10, projectId: id, name: "Nine Grid Test", memo: "", expectedPhotoCount: null, sources: [], photoStates: {},
      worktableDraft: { projectId: id, entryOrder: [], placements: {}, groups: [], links: [], pileOrder: [], pilePlacements: {}, frameOrder: [], frames: {} },
      sequenceIds: [], versionIds: [], layoutIds: [], revision: 0, createdAt, updatedAt: createdAt, lastOpenedAt: createdAt });
    await new Promise<void>((resolve, reject) => { transaction.oncomplete = () => resolve(); transaction.onerror = () => reject(transaction.error); });
    db.close();
  }, projectId);
  await page.goto(`/#/projects/${projectId}/table`);
  await page.getByRole("button", { name: "Frame templates" }).click();
  await page.getByRole("button", { name: /^Plain Page/ }).click();
  await page.getByRole("button", { name: /Square Nine Grid 9 slots/ }).click();
  const frame = page.locator("[data-frame-id]");
  const settings = page.getByRole("complementary", { name: "Frame settings" });
  await expect(frame.locator("[data-frame-slot-id]")).toHaveCount(9);
  const pageSize = await frame.locator(".table-frame-page").evaluate((node) => ({ width: (node as HTMLElement).style.width, height: (node as HTMLElement).style.height }));
  expect(pageSize.width).toBe(pageSize.height);
  await settings.getByRole("button", { name: "Paper color", exact: true }).click();
  await settings.getByRole("option", { name: "Charcoal", exact: true }).click();
  await expect(frame.locator(".table-frame-page")).toHaveClass(/is-black/);
  await page.screenshot({ path: testInfo.outputPath("frame-settings.png") });
  await expect(settings.getByRole("slider", { name: "Corner radius" })).toHaveCount(0);
  await expect(settings.getByRole("spinbutton", { name: "Bleed mm" })).toHaveCount(0);
  await expect(settings.getByRole("spinbutton", { name: "Margin top mm" })).toHaveCount(0);
  await expect(settings.getByRole("spinbutton", { name: "Gap mm" })).toHaveCount(0);
  const firstId = await frame.locator("[data-frame-slot-id]").first().getAttribute("data-frame-slot-id");
  await frame.locator("[data-frame-slot-id]").first().click();
  await expect(settings.getByText("PHOTO BOX 01")).toBeVisible();
  await expect(settings.getByRole("group", { name: "Template" })).toBeVisible();
  await expect(settings.getByRole("button", { name: "Paper color", exact: true })).toBeVisible();
  await settings.getByRole("slider", { name: "Corner radius" }).focus();
  await page.keyboard.press("End");
  await expect(frame.locator(".table-frame-photo-clip").first()).toHaveCSS("border-radius", "32px");
  await expect(frame.locator(".table-frame-photo-clip").nth(1)).toHaveCSS("border-radius", "0px");
  await page.screenshot({ path: testInfo.outputPath("photo-box-settings.png") });
  await settings.getByRole("button", { name: "Front photo box" }).click();
  await expect(frame.locator("[data-frame-slot-id]").last()).toHaveAttribute("data-frame-slot-id", firstId!);
  await page.keyboard.press("Delete");
  await expect(frame.locator("[data-frame-slot-id]")).toHaveCount(8);
  await expect(settings.getByRole("button", { name: "Add photo box" })).toBeVisible();
  await page.reload();
  await expect(page.locator("[data-frame-id] .table-frame-page")).toHaveClass(/is-black/);
  await expect(page.locator("[data-frame-id] [data-frame-slot-id]")).toHaveCount(8);
});

test("keeps Table photos above existing Frames until Front is chosen", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/");
  const projectId = `frame-layer-${crypto.randomUUID()}`;
  await page.evaluate(async (id) => {
    const request = indexedDB.open("photoflex-mvp");
    const db = await new Promise<IDBDatabase>((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
    const createdAt = new Date().toISOString();
    const transaction = db.transaction("projects", "readwrite");
    transaction.objectStore("projects").put({ schemaVersion: 10, projectId: id, name: "Frame Layer Test", memo: "", expectedPhotoCount: null, sources: [], photoStates: {},
      worktableDraft: { projectId: id, entryOrder: ["card-layer"], placements: { "card-layer": { id: "card-layer", photoId: "photo-layer", z: 1, x: 180, y: 150, width: 200, height: 160, filename: "Layer.jpg" } },
        groups: [], links: [], pileOrder: [], pilePlacements: {}, frameOrder: [], frames: {} },
      sequenceIds: [], versionIds: [], layoutIds: [], revision: 0, createdAt, updatedAt: createdAt, lastOpenedAt: createdAt });
    await new Promise<void>((resolve, reject) => { transaction.oncomplete = () => resolve(); transaction.onerror = () => reject(transaction.error); });
    db.close();
  }, projectId);
  await page.goto(`/#/projects/${projectId}/table`);
  await page.getByRole("button", { name: "Frame templates" }).click();
  await page.getByRole("button", { name: /^Plain Page/ }).click();
  await page.getByRole("button", { name: /Single 1 slots/ }).click();
  const frame = page.locator("[data-frame-id]");
  const photo = page.locator("[data-worktable-photo-id]");
  await expect(frame).toBeVisible();
  await expect(photo).toBeVisible();
  await page.waitForFunction(async (id) => {
    const request = indexedDB.open("photoflex-mvp");
    const db = await new Promise<IDBDatabase>((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
    const read = db.transaction("projects", "readonly").objectStore("projects").get(id);
    const workspace = await new Promise<{ worktableDraft?: { frameOrder?: string[] } }>((resolve, reject) => { read.onsuccess = () => resolve(read.result); read.onerror = () => reject(read.error); });
    db.close();
    return workspace?.worktableDraft?.frameOrder?.length === 1;
  }, projectId);
  await page.evaluate(async (id) => {
    const request = indexedDB.open("photoflex-mvp");
    const db = await new Promise<IDBDatabase>((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
    const transaction = db.transaction("projects", "readwrite");
    const store = transaction.objectStore("projects");
    const read = store.get(id);
    const workspace = await new Promise<any>((resolve, reject) => { read.onsuccess = () => resolve(read.result); read.onerror = () => reject(read.error); });
    const frameId = workspace.worktableDraft.frameOrder[0];
    Object.assign(workspace.worktableDraft.frames[frameId], { x: 120, y: 100, z: 999 });
    store.put(workspace);
    await new Promise<void>((resolve, reject) => { transaction.oncomplete = () => resolve(); transaction.onerror = () => reject(transaction.error); });
    db.close();
  }, projectId);
  await page.reload();
  await expect(frame).toBeVisible();
  const overlapIsPhoto = () => page.evaluate(() => {
    const frameRect = document.querySelector(".table-frame-page")!.getBoundingClientRect();
    const photoRect = document.querySelector("[data-worktable-photo-id]")!.getBoundingClientRect();
    const left = Math.max(frameRect.left, photoRect.left), right = Math.min(frameRect.right, photoRect.right);
    const top = Math.max(frameRect.top, photoRect.top), bottom = Math.min(frameRect.bottom, photoRect.bottom);
    if (left >= right || top >= bottom) return "no-overlap";
    const hit = document.elementFromPoint((left + right) / 2, (top + bottom) / 2) as HTMLElement | null;
    return hit?.closest("[data-worktable-photo-id]") ? "photo" : hit?.closest("[data-frame-id]") ? "frame" : "other";
  });
  expect(await overlapIsPhoto()).toBe("photo");
  await frame.locator(".table-frame-title").click();
  expect(await overlapIsPhoto()).toBe("photo");
  await page.getByRole("complementary", { name: "Frame settings" }).getByRole("button", { name: "Front", exact: true }).click();
  expect(await overlapIsPhoto()).toBe("frame");
});

test("browses all template families and persists paper, captions and dark frame finishes", async ({ page }, testInfo) => {
  test.setTimeout(90_000);
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "Projects" })).toBeVisible();
  const projectId = `frame-families-${crypto.randomUUID()}`;
  await page.evaluate(async (id) => {
    const request = indexedDB.open("photoflex-mvp");
    const db = await new Promise<IDBDatabase>((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
    const createdAt = new Date().toISOString();
    const canvas = document.createElement("canvas"); canvas.width = 1200; canvas.height = 900;
    const ctx = canvas.getContext("2d")!;
    ctx.fillStyle = "#9fb9c5"; ctx.fillRect(0, 0, 1200, 900);
    ctx.fillStyle = "#546653"; ctx.beginPath(); ctx.moveTo(0, 600); ctx.lineTo(430, 280); ctx.lineTo(900, 700); ctx.lineTo(1200, 500); ctx.lineTo(1200, 900); ctx.lineTo(0, 900); ctx.fill();
    ctx.fillStyle = "#c9bd9e"; ctx.beginPath(); ctx.moveTo(420, 900); ctx.lineTo(570, 540); ctx.lineTo(650, 540); ctx.lineTo(920, 900); ctx.fill();
    const blob = await new Promise<Blob>((resolve) => canvas.toBlob((value) => resolve(value!), "image/jpeg"));
    const directory = await navigator.storage.getDirectory();
    const handle = await directory.getFileHandle(`${id}.jpg`, { create: true });
    const writable = await handle.createWritable(); await writable.write(blob); await writable.close();
    const sourceId = `source-${id}`, photoId = `photo-${id}`, cardId = `card-${id}`;
    const transaction = db.transaction(["projects", "photo-index", "photo-file-handles"], "readwrite");
    transaction.objectStore("photo-index").put({ id: photoId, sourceId, relativePath: `${id}.jpg`, locationKind: "file-handle", width: 1200, height: 900 });
    transaction.objectStore("photo-file-handles").put({ photoId, handle });
    transaction.objectStore("projects").put({ schemaVersion: 10, projectId: id, name: "Frame Templates", memo: "", expectedPhotoCount: null, sources: [{ id: sourceId, displayName: "Sample", kind: "external-files", createdAt }], photoStates: {},
      worktableDraft: { projectId: id, entryOrder: [cardId], placements: { [cardId]: { id: cardId, photoId, filename: "Sample.jpg", x: 180, y: 150, z: 1, width: 180, height: 135 } }, groups: [], links: [], pileOrder: [], pilePlacements: {}, frameOrder: [], frames: {} },
      sequenceIds: [], versionIds: [], layoutIds: [], revision: 0, createdAt, updatedAt: createdAt, lastOpenedAt: createdAt });
    await new Promise<void>((resolve, reject) => { transaction.oncomplete = () => resolve(); transaction.onerror = () => reject(transaction.error); });
    db.close();
  }, projectId);
  await page.goto(`/#/projects/${projectId}/table`);
  await page.locator("[data-worktable-photo-id]").click();
  await page.getByRole("button", { name: "Frame templates" }).click();
  const menu = page.getByRole("dialog", { name: "Frame templates" });
  await expect(menu.getByRole("navigation", { name: "Template families" }).getByRole("button")).toHaveCount(4);
  await expect(menu.getByRole("button", { name: /^Sheets/ })).toHaveCount(0);
  await menu.getByRole("button", { name: /^Instax/ }).click();
  await expect(menu.getByRole("button", { name: /Instax mini/ })).toBeVisible();
  await expect(menu.getByRole("button", { name: /Instax square/ })).toBeVisible();
  await expect(menu.getByRole("button", { name: /Instax wide/ })).toBeVisible();
  await menu.getByRole("button", { name: /Instax mini/ }).click();
  const frame = page.locator("[data-frame-id]");
  const settings = page.getByRole("complementary", { name: "Frame settings" });
  await expect(frame.locator(".table-frame-photo-clip img")).toBeVisible();
  await expect(frame.locator(".table-frame-page")).toHaveCSS("background-color", "rgb(255, 255, 255)");
  const photoBox = frame.locator("[data-frame-slot-id]").first();
  const photo = photoBox.locator("img");
  const initialWidth = await photo.evaluate((node) => parseFloat(node.style.width));
  const worldTransform = await page.locator(".worktable-world").getAttribute("style");
  await photoBox.dblclick();
  await expect(settings.getByRole("button", { name: "Cancel crop", exact: true })).toBeVisible();
  const wheelAtPhoto = (deltaY: number) => photoBox.evaluate((node, delta) => {
    const bounds = node.getBoundingClientRect();
    const event = new WheelEvent("wheel", { deltaY: delta, clientX: bounds.left + bounds.width * .6,
      clientY: bounds.top + bounds.height * .4, bubbles: true, cancelable: true });
    node.dispatchEvent(event);
    return event.defaultPrevented;
  }, deltaY);
  expect(await wheelAtPhoto(-120)).toBe(true);
  await expect.poll(() => photo.evaluate((node) => parseFloat(node.style.width))).toBeGreaterThan(initialWidth);
  await expect(page.locator(".worktable-world")).toHaveAttribute("style", worldTransform!);
  await settings.getByRole("button", { name: "Cancel crop", exact: true }).click();
  await expect.poll(() => photo.evaluate((node) => parseFloat(node.style.width))).toBe(initialWidth);
  await photoBox.dblclick();
  expect(await wheelAtPhoto(-120)).toBe(true);
  await settings.getByRole("button", { name: "Done", exact: true }).click();
  const savedWidth = await photo.evaluate((node) => parseFloat(node.style.width));
  expect(savedWidth).toBeGreaterThan(initialWidth);
  await photoBox.dblclick();
  expect(await wheelAtPhoto(120)).toBe(true);
  await expect.poll(() => photo.evaluate((node) => parseFloat(node.style.width))).toBeLessThan(savedWidth);
  await page.keyboard.press("Escape");
  await expect.poll(() => photo.evaluate((node) => parseFloat(node.style.width))).toBe(savedWidth);
  await expect(frame.locator(".table-frame-inner-edge")).toHaveCount(0);
  await expect(settings.getByRole("group", { name: "Template" }).getByRole("button")).toHaveCount(3);
  await settings.getByLabel("Frame caption").fill("Shanghai, 2026");
  await settings.getByLabel("Frame caption").press("Tab");
  await expect(frame.locator(".table-frame-instant-caption")).toHaveText("Shanghai, 2026");
  await settings.getByRole("button", { name: "Paper color", exact: true }).click();
  await settings.getByRole("option", { name: "Warm Ivory", exact: true }).click();
  await settings.getByRole("button", { name: "Paper material", exact: true }).click();
  await settings.getByRole("option", { name: "Fine cotton paper", exact: true }).click();
  await expect(frame.locator(".layout-paper-backdrop")).toHaveCSS("background-color", "rgb(244, 239, 229)");
  const texture = await frame.locator(".layout-paper-backdrop").evaluate((node) => getComputedStyle(node, "::before").filter);
  expect(texture).toBe("none");
  await settings.getByRole("button", { name: "Paper color", exact: true }).click();
  await settings.getByRole("option", { name: "Custom", exact: true }).click();
  await settings.getByLabel("Paper color hex").fill("#F2EADE");
  await settings.getByLabel("Paper color hex").press("Tab");
  await settings.getByRole("button", { name: "Done", exact: true }).click();
  await expect(frame.locator(".table-frame-page")).toHaveCSS("background-color", "rgb(242, 234, 222)");
  await settings.getByLabel("Caption font", { exact: true }).selectOption("architects-daughter");
  await settings.getByRole("spinbutton", { name: "Caption size pt", exact: true }).fill("12");
  await settings.getByRole("spinbutton", { name: "Caption size pt", exact: true }).press("Tab");
  await expect(settings.getByRole("spinbutton", { name: /^Caption [XYWH] mm$/ })).toHaveCount(0);
  const caption = frame.locator(".table-frame-instant-caption");
  await expect(caption).toHaveCSS("font-size", "12px");
  const before = await caption.evaluate((node) => parseFloat((node as HTMLElement).style.left));
  const box = (await caption.boundingBox())!;
  await page.mouse.move(box.x + 8, box.y + 5); await page.mouse.down(); await page.mouse.move(box.x + 24, box.y - 6, { steps: 4 }); await page.mouse.up();
  expect(await caption.evaluate((node) => parseFloat((node as HTMLElement).style.left))).toBeGreaterThan(before);
  await page.screenshot({ path: testInfo.outputPath("instax-template.png") });
  await settings.getByLabel("Template family").selectOption("polaroid");
  for (const name of ["Classic 600", "Square type", "Land camera"]) {
    await settings.getByRole("button", { name, exact: true }).click();
    await expect(frame.locator("[data-frame-slot-id]")).toHaveCount(1);
  }
  await settings.getByLabel("Template family").selectOption("frames");
  await expect(settings.getByRole("group", { name: "Template" }).getByRole("button")).toHaveCount(1);
  await settings.getByRole("group", { name: "Frame edge color" }).getByRole("button", { name: "Walnut", exact: true }).click();
  await expect(frame.locator(".table-frame-gallery-edge")).toHaveCSS("border-top-color", "rgb(73, 48, 37)");
  await settings.getByRole("button", { name: "Paper color", exact: true }).click();
  await settings.getByRole("option", { name: "Ink Blue", exact: true }).click();
  await expect(frame.locator(".table-frame-page")).toHaveCSS("background-color", "rgb(30, 43, 69)");
  await settings.getByRole("spinbutton", { name: "Frame edge width mm", exact: true }).fill("10");
  await settings.getByRole("spinbutton", { name: "Frame edge width mm", exact: true }).press("Tab");
  await settings.getByLabel("Frame material", { exact: true }).selectOption("wood");
  await settings.getByLabel("Frame shadow strength").focus(); await page.keyboard.press("End");
  await settings.getByRole("spinbutton", { name: "Photo elevation mm", exact: true }).fill("3");
  await settings.getByRole("spinbutton", { name: "Photo elevation mm", exact: true }).press("Tab");
  await settings.getByRole("group", { name: "Inner edge", exact: true }).getByRole("button", { name: "Mat bevel", exact: true }).click();
  await settings.getByRole("spinbutton", { name: "Inner edge width mm", exact: true }).fill("2");
  await settings.getByRole("spinbutton", { name: "Inner edge width mm", exact: true }).press("Tab");
  await expect(frame.locator(".table-frame-inner-edge")).toHaveCount(1);
  await expect(frame.locator(".table-frame-gallery-edge")).toHaveClass(/edge-material-wood/);
  const downloadEvent = page.waitForEvent("download");
  await settings.getByRole("button", { name: "Export JPEG", exact: true }).click();
  const download = await downloadEvent;
  expect(download.suggestedFilename()).toMatch(/\.jpeg$/);
  const stream = await download.createReadStream();
  const chunks: Buffer[] = [];
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk));
  const bytes = Buffer.concat(chunks);
  expect([...bytes.subarray(0, 2)]).toEqual([0xff, 0xd8]);
  const exported = await page.evaluate(async (base64) => {
    const data = Uint8Array.from(atob(base64), (char) => char.charCodeAt(0));
    const image = await createImageBitmap(new Blob([data], { type: "image/jpeg" }));
    const canvas = document.createElement("canvas"); canvas.width = image.width; canvas.height = image.height;
    const context = canvas.getContext("2d")!; context.drawImage(image, 0, 0);
    const sample = (x: number, y: number) => [...context.getImageData(Math.round(x * image.width), Math.round(y * image.height), 1, 1).data].slice(0, 3);
    const result = { width: image.width, height: image.height, border: sample(.01, .5), paper: sample(.15, .5), photo: sample(.5, .5) };
    image.close(); return result;
  }, bytes.toString("base64"));
  expect(exported.width).toBe(6554);
  expect(exported.height).toBe(8192);
  expect(exported.border.reduce((sum, value) => sum + value, 0)).toBeGreaterThan(60);
  expect(exported.paper[2]).toBeGreaterThan(exported.paper[0]);
  expect(exported.photo).not.toEqual(exported.paper);
  await download.saveAs(testInfo.outputPath("gallery-frame.jpeg"));
  await expect(settings.getByRole("status")).toHaveText("JPEG download started.");
  await expect(frame.locator(".table-frame-edge-surface")).toHaveCount(4);
  await settings.getByRole("button", { name: "Contain", exact: true }).click();
  const footprint = await frame.locator("[data-frame-slot-id]").evaluate((slot) => {
    const image = slot.querySelector("img") as HTMLElement;
    const edge = slot.querySelector(".table-frame-inner-edge") as HTMLElement;
    const elevation = slot.querySelector(".table-frame-photo-elevation") as HTMLElement;
    return { slotHeight: parseFloat((slot as HTMLElement).style.height), imageHeight: parseFloat(image.style.height),
      edgeHeight: parseFloat(edge.style.height) - parseFloat(edge.style.borderWidth) * 2, elevationHeight: parseFloat(elevation.style.height) };
  });
  expect(footprint.edgeHeight).toBeCloseTo(footprint.imageHeight);
  expect(footprint.elevationHeight).toBeCloseTo(footprint.imageHeight);
  expect(footprint.edgeHeight).toBeLessThan(footprint.slotHeight);
  await page.setViewportSize({ width: 1280, height: 800 });
  await page.screenshot({ path: testInfo.outputPath("gallery-template-1280.png") });
  await page.reload();
  await expect(frame.locator(".table-frame-gallery-edge")).toHaveCSS("border-top-color", "rgb(73, 48, 37)");
  await expect(frame.locator(".table-frame-page")).toHaveCSS("background-color", "rgb(30, 43, 69)");
  await expect(frame.locator(".layout-paper-backdrop")).toHaveAttribute("style", /fine-paper/);
  await expect(frame.locator(".table-frame-gallery-edge")).toHaveClass(/edge-material-wood/);
  await expect(frame.locator(".table-frame-inner-edge")).toHaveCount(1);
  await expect(frame.locator(".table-frame-instant-caption")).toHaveCSS("font-size", "12px");
  await frame.locator(".table-frame-title").click();
  await settings.getByLabel("Template family").selectOption("instax");
  await expect(frame.locator(".table-frame-instant-caption")).toHaveText("Shanghai, 2026");
});
